/**
 * West African Countries, States/Regions, and Major Cities
 */

export interface LocationData {
  [country: string]: {
    [state: string]: string[];
  };
}

const locationData: LocationData = {
  Nigeria: {
    Abia: ['Aba', 'Umuahia', 'Ohafia'],
    Adamawa: ['Yola', 'Mubi', 'Jimeta', 'Numan'],
    'Akwa Ibom': ['Uyo', 'Eket', 'Ikot Ekpene', 'Oron'],
    Anambra: ['Awka', 'Onitsha', 'Nnewi', 'Ekwulobia'],
    Bauchi: ['Bauchi', 'Azare', 'Misau'],
    Bayelsa: ['Yenagoa', 'Ogbia', 'Brass'],
    Benue: ['Makurdi', 'Otukpo', 'Gboko', 'Katsina-Ala'],
    Borno: ['Maiduguri', 'Biu', 'Bama'],
    'Cross River': ['Calabar', 'Ogoja', 'Ikom'],
    Delta: ['Asaba', 'Warri', 'Sapele', 'Ughelli'],
    Ebonyi: ['Abakaliki', 'Afikpo', 'Onueke'],
    Edo: ['Benin City', 'Auchi', 'Ekpoma'],
    Ekiti: ['Ado-Ekiti', 'Ikere', 'Efon-Alaaye'],
    Enugu: ['Enugu', 'Nsukka', 'Agbani'],
    'FCT Abuja': ['Abuja', 'Gwagwalada', 'Kuje', 'Kubwa'],
    Gombe: ['Gombe', 'Billiri', 'Kaltungo'],
    Imo: ['Owerri', 'Orlu', 'Okigwe'],
    Jigawa: ['Dutse', 'Hadejia', 'Kazaure'],
    Kaduna: ['Kaduna', 'Zaria', 'Kafanchan'],
    Kano: ['Kano', 'Wudil', 'Gaya'],
    Katsina: ['Katsina', 'Daura', 'Funtua'],
    Kebbi: ['Birnin Kebbi', 'Argungu', 'Zuru'],
    Kogi: ['Lokoja', 'Okene', 'Idah'],
    Kwara: ['Ilorin', 'Offa', 'Jebba'],
    Lagos: ['Lagos', 'Ikeja', 'Lekki', 'Victoria Island', 'Ikorodu', 'Epe', 'Badagry'],
    Nasarawa: ['Lafia', 'Keffi', 'Akwanga'],
    Niger: ['Minna', 'Bida', 'Suleja', 'Kontagora'],
    Ogun: ['Abeokuta', 'Sagamu', 'Ijebu-Ode', 'Ota'],
    Ondo: ['Akure', 'Ondo', 'Owo', 'Ikare'],
    Osun: ['Osogbo', 'Ile-Ife', 'Ilesa', 'Ede'],
    Oyo: ['Ibadan', 'Ogbomoso', 'Oyo', 'Iseyin'],
    Plateau: ['Jos', 'Bukuru', 'Pankshin'],
    Rivers: ['Port Harcourt', 'Bonny', 'Degema', 'Obio-Akpor'],
    Sokoto: ['Sokoto', 'Tambuwal', 'Wurno'],
    Taraba: ['Jalingo', 'Wukari', 'Bali'],
    Yobe: ['Damaturu', 'Potiskum', 'Gashua'],
    Zamfara: ['Gusau', 'Kaura Namoda', 'Talata Mafara'],
  },
  Ghana: {
    'Greater Accra': ['Accra', 'Tema', 'Madina', 'Teshie'],
    Ashanti: ['Kumasi', 'Obuasi', 'Ejisu', 'Mampong'],
    Western: ['Takoradi', 'Sekondi', 'Tarkwa'],
    Eastern: ['Koforidua', 'Nkawkaw', 'Akosombo'],
    Central: ['Cape Coast', 'Winneba', 'Kasoa'],
    Volta: ['Ho', 'Hohoe', 'Keta', 'Kpando'],
    Northern: ['Tamale', 'Yendi', 'Salaga'],
    'Upper East': ['Bolgatanga', 'Bawku', 'Navrongo'],
    'Upper West': ['Wa', 'Tumu', 'Lawra'],
    'Bono East': ['Techiman', 'Kintampo', 'Atebubu'],
    Bono: ['Sunyani', 'Berekum', 'Dormaa Ahenkro'],
    Ahafo: ['Goaso', 'Bechem', 'Duayaw-Nkwanta'],
    'North East': ['Nalerigu', 'Gambaga', 'Walewale'],
    Savannah: ['Damongo', 'Bole', 'Sawla'],
    'Oti Region': ['Dambai', 'Jasikan', 'Kadjebi'],
    'Western North': ['Sefwi Wiawso', 'Bibiani', 'Enchi'],
  },
  Senegal: {
    Dakar: ['Dakar', 'Pikine', 'Guédiawaye', 'Rufisque'],
    Thiès: ['Thiès', 'Mbour', 'Tivaouane'],
    'Saint-Louis': ['Saint-Louis', 'Richard-Toll', 'Dagana'],
    Diourbel: ['Diourbel', 'Touba', 'Bambey'],
    Kaolack: ['Kaolack', 'Nioro du Rip', 'Guinguinéo'],
    Ziguinchor: ['Ziguinchor', 'Bignona', 'Oussouye'],
    Fatick: ['Fatick', 'Foundiougne', 'Gossas'],
    Kolda: ['Kolda', 'Vélingara', 'Médina Yoro Foulah'],
    Tambacounda: ['Tambacounda', 'Kédougou', 'Bakel'],
    Louga: ['Louga', 'Linguère', 'Kébémer'],
    Matam: ['Matam', 'Ranérou', 'Kanel'],
    Kaffrine: ['Kaffrine', 'Birkelane', 'Koungheul'],
    Sédhiou: ['Sédhiou', 'Bounkiling', 'Goudomp'],
    Kédougou: ['Kédougou', 'Salémata', 'Saraya'],
  },
  "Côte d'Ivoire": {
    Abidjan: ['Abidjan', 'Cocody', 'Yopougon', 'Plateau'],
    Yamoussoukro: ['Yamoussoukro'],
    Bouaké: ['Bouaké'],
    Daloa: ['Daloa'],
    'San-Pédro': ['San-Pédro'],
    Korhogo: ['Korhogo'],
    Man: ['Man'],
    Gagnoa: ['Gagnoa'],
  },
  Cameroon: {
    Centre: ['Yaoundé', 'Mbalmayo', 'Obala'],
    Littoral: ['Douala', 'Nkongsamba', 'Edéa'],
    West: ['Bafoussam', 'Dschang', 'Mbouda'],
    Northwest: ['Bamenda', 'Kumbo', 'Wum'],
    Southwest: ['Buea', 'Limbe', 'Kumba'],
    North: ['Garoua', 'Guider', 'Pitoa'],
    'Far North': ['Maroua', 'Mokolo', 'Kousseri'],
    Adamaoua: ['Ngaoundéré', 'Meiganga', 'Tibati'],
    East: ['Bertoua', 'Batouri', 'Yokadouma'],
    South: ['Ebolowa', 'Kribi', 'Sangmélima'],
  },
  Togo: {
    Maritime: ['Lomé', 'Tsévié', 'Aného'],
    Plateaux: ['Atakpamé', 'Kpalimé', 'Notsé'],
    Centrale: ['Sokodé', 'Tchamba', 'Sotouboua'],
    Kara: ['Kara', 'Bassar', 'Niamtougou'],
    Savanes: ['Dapaong', 'Mango', 'Tandjoaré'],
  },
  Benin: {
    Littoral: ['Cotonou'],
    Atlantique: ['Ouidah', 'Abomey-Calavi', 'Allada'],
    Ouémé: ['Porto-Novo', 'Adjarra', 'Avrankou'],
    Zou: ['Abomey', 'Bohicon', 'Covè'],
    Borgou: ['Parakou', 'Nikki', 'N\'Dali'],
    Alibori: ['Kandi', 'Malanville', 'Banikoara'],
    Atacora: ['Natitingou', 'Tanguiéta', 'Kouandé'],
    Donga: ['Djougou', 'Bassila', 'Copargo'],
    Collines: ['Savalou', 'Dassa-Zoumé', 'Savè'],
    Mono: ['Lokossa', 'Athiémé', 'Comè'],
    Couffo: ['Aplahoué', 'Djakotomey', 'Dogbo'],
    Plateau: ['Sakété', 'Kétou', 'Pobè'],
  },
  Mali: {
    Bamako: ['Bamako'],
    Sikasso: ['Sikasso', 'Koutiala', 'Bougouni'],
    Ségou: ['Ségou', 'San', 'Bla'],
    Mopti: ['Mopti', 'Djenné', 'Bandiagara'],
    Koulikoro: ['Koulikoro', 'Kati', 'Kolokani'],
    Kayes: ['Kayes', 'Kita', 'Nioro du Sahel'],
    Gao: ['Gao', 'Ansongo', 'Bourem'],
    Tombouctou: ['Tombouctou', 'Diré', 'Goundam'],
    Kidal: ['Kidal', 'Tessalit', 'Aguelhok'],
  },
  'Burkina Faso': {
    'Centre (Ouagadougou)': ['Ouagadougou'],
    'Hauts-Bassins': ['Bobo-Dioulasso', 'Houndé'],
    Boucle_du_Mouhoun: ['Dédougou', 'Boromo', 'Nouna'],
    Est: ['Fada N\'Gourma', 'Diapaga'],
    Nord: ['Ouahigouya', 'Titao'],
    'Centre-Ouest': ['Koudougou', 'Réo', 'Léo'],
    Sahel: ['Dori', 'Djibo', 'Gorom-Gorom'],
    'Centre-Est': ['Tenkodogo', 'Koupéla'],
    'Centre-Nord': ['Kaya', 'Kongoussi'],
    Cascades: ['Banfora', 'Sindou'],
    'Centre-Sud': ['Manga', 'Pô', 'Kombissiri'],
    'Sud-Ouest': ['Gaoua', 'Batié', 'Dano'],
    'Plateau-Central': ['Ziniaré', 'Zorgho'],
  },
  Niger: {
    Niamey: ['Niamey'],
    Zinder: ['Zinder', 'Mirriah', 'Tanout'],
    Maradi: ['Maradi', 'Tessaoua', 'Aguié'],
    Tahoua: ['Tahoua', 'Madaoua', 'Konni'],
    Agadez: ['Agadez', 'Arlit'],
    Dosso: ['Dosso', 'Gaya', 'Dogondoutchi'],
    Diffa: ['Diffa', 'Maïné-Soroa'],
    Tillabéri: ['Tillabéri', 'Ouallam', 'Say'],
  },
  Guinea: {
    Conakry: ['Conakry'],
    Kindia: ['Kindia', 'Mamou', 'Dalaba'],
    Boké: ['Boké', 'Kamsar', 'Boffa'],
    Labé: ['Labé', 'Pita', 'Tougué'],
    Kankan: ['Kankan', 'Kouroussa', 'Siguiri'],
    Faranah: ['Faranah', 'Kissidougou', 'Dabola'],
    'N\'Zérékoré': ['N\'Zérékoré', 'Macenta', 'Guéckédou'],
  },
  'Sierra Leone': {
    Western: ['Freetown', 'Waterloo'],
    Northern: ['Makeni', 'Kambia', 'Port Loko'],
    Southern: ['Bo', 'Kenema', 'Moyamba'],
    Eastern: ['Kenema', 'Kailahun', 'Koidu'],
    Northwestern: ['Makeni', 'Kabala'],
  },
  Liberia: {
    Montserrado: ['Monrovia', 'Paynesville', 'Bensonville'],
    Nimba: ['Sanniquellie', 'Ganta', 'Saclepea'],
    Bong: ['Gbarnga', 'Suakoko', 'Totota'],
    Lofa: ['Voinjama', 'Foya', 'Kolahun'],
    'Grand Bassa': ['Buchanan'],
    Margibi: ['Kakata', 'Harbel'],
    'Grand Cape Mount': ['Robertsport'],
  },
  'The Gambia': {
    'Banjul (Capital)': ['Banjul'],
    'Kanifing (Greater Banjul)': ['Serekunda', 'Bakau', 'Fajara'],
    'West Coast': ['Brikama', 'Gunjur', 'Sanyang'],
    'North Bank': ['Farafenni', 'Kerewan'],
    'Lower River': ['Mansakonko', 'Soma'],
    'Central River': ['Janjanbureh', 'Bansang'],
    'Upper River': ['Basse Santa Su', 'Fatoto'],
  },
  'Guinea-Bissau': {
    Bissau: ['Bissau'],
    Gabú: ['Gabú'],
    Bafatá: ['Bafatá'],
    Cacheu: ['Cacheu', 'Canchungo'],
    Biombo: ['Quinhámel'],
    Oio: ['Farim', 'Mansoa'],
  },
  'Cape Verde': {
    Santiago: ['Praia', 'Assomada', 'Tarrafal'],
    'São Vicente': ['Mindelo'],
    'Santo Antão': ['Ribeira Grande', 'Porto Novo', 'Paul'],
    Sal: ['Espargos', 'Santa Maria'],
    Fogo: ['São Filipe'],
    'Boa Vista': ['Sal Rei'],
  },
};

export function getCountries(): string[] {
  return Object.keys(locationData).sort();
}

export function getStates(country: string): string[] {
  return country && locationData[country]
    ? Object.keys(locationData[country]).sort()
    : [];
}

export function getCities(country: string, state: string): string[] {
  return country && state && locationData[country]?.[state]
    ? locationData[country][state].sort()
    : [];
}
